// Atlas Ally — Country Intelligence Data
// Each country has: advisory level, emergency numbers, news RSS feeds,
// State Dept URL, border crossings, health notices, currency, capital

const COUNTRIES = {
  JO: {
    name: 'Jordan',
    flag: '🇯🇴',
    capital: 'Amman',
    currency: 'Jordanian Dinar (JOD)',
    language: 'Arabic',
    timezone: 'Asia/Amman',
    center: [31.5, 36.5],
    zoom: 7,
    advisoryLevel: 2, // 1=normal 2=elevated 3=high 4=critical
    advisoryText: 'Exercise increased caution due to terrorism and civil unrest.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/jordan-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/jordan',
    emergency: { police: '911', fire: '199', ambulance: '911', tourism: '911' },
    borderCrossings: [
      { name: 'King Hussein Bridge (Allenby)', status: 'open', note: 'Jordan↔West Bank' },
      { name: 'Wadi Araba / Yitzhak Rabin', status: 'open', note: 'Jordan↔Israel south' },
      { name: 'Sheikh Hussein / Jordan River', status: 'open', note: 'Jordan↔Israel north' },
      { name: 'Jaber / Nassib', status: 'restricted', note: 'Jordan↔Syria, limited hours' },
      { name: 'Omari / Turabil', status: 'open', note: 'Jordan↔Saudi Arabia' },
    ],
    healthNotices: [
      'Routine vaccinations recommended (Hepatitis A, Typhoid)',
      'No malaria risk in urban areas',
      'Medical facilities adequate in Amman, limited elsewhere',
    ],
    newsFeed: [
      { name: 'Jordan Times', url: 'https://jordantimes.com/feed', type: 'rss' },
      { name: 'Al Jazeera', url: 'https://www.aljazeera.com/xml/rss/all.xml', type: 'rss' },
      { name: 'Reuters ME', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Amman', lat: 31.9539, lng: 35.9106 },
      { name: 'Zarqa', lat: 32.0728, lng: 36.0877 },
      { name: 'Irbid', lat: 32.5556, lng: 35.8500 },
      { name: 'Aqaba', lat: 29.5267, lng: 35.0078 },
      { name: 'Mafraq', lat: 32.3431, lng: 36.2114 },
      { name: 'Karak', lat: 31.1823, lng: 35.7054 },
      { name: 'Salt', lat: 32.0384, lng: 35.7271 },
      { name: 'Madaba', lat: 31.7154, lng: 35.7939 },
      { name: 'Tafilah', lat: 30.8362, lng: 35.6088 },
      { name: 'Ajloun', lat: 32.3325, lng: 35.7517 },
    ],
  },

  UA: {
    name: 'Ukraine',
    flag: '🇺🇦',
    capital: 'Kyiv',
    currency: 'Ukrainian Hryvnia (UAH)',
    language: 'Ukrainian',
    timezone: 'Europe/Kiev',
    center: [49.0, 31.0],
    zoom: 6,
    advisoryLevel: 4,
    advisoryText: 'Do not travel. Active armed conflict throughout the country.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/ukraine-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/ukraine',
    emergency: { police: '102', fire: '101', ambulance: '103', general: '112' },
    borderCrossings: [
      { name: 'Medyka / Shehyni', status: 'open', note: 'Ukraine↔Poland' },
      { name: 'Uzhhorod / Vyšné Nemecké', status: 'open', note: 'Ukraine↔Slovakia' },
      { name: 'Chop / Záhony', status: 'open', note: 'Ukraine↔Hungary' },
      { name: 'Porubne / Siret', status: 'open', note: 'Ukraine↔Romania' },
      { name: 'Russia border', status: 'closed', note: 'All crossings closed' },
      { name: 'Belarus border', status: 'closed', note: 'All crossings closed' },
    ],
    healthNotices: [
      'Medical infrastructure severely damaged in conflict zones',
      'Blood supply and medication shortages reported',
      'Psychological support resources available via NGOs',
    ],
    newsFeed: [
      { name: 'Kyiv Independent', url: 'https://kyivindependent.com/feed/', type: 'rss' },
      { name: 'Reuters Ukraine', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
      { name: 'BBC Ukraine', url: 'https://feeds.bbci.co.uk/news/world/europe/rss.xml', type: 'rss' },
    ],
    cities: [
      { name: 'Kyiv', lat: 50.4501, lng: 30.5234 },
      { name: 'Kharkiv', lat: 49.9935, lng: 36.2304 },
      { name: 'Odesa', lat: 46.4825, lng: 30.7233 },
      { name: 'Lviv', lat: 49.8397, lng: 24.0297 },
      { name: 'Zaporizhzhia', lat: 47.8388, lng: 35.1396 },
      { name: 'Dnipro', lat: 48.4647, lng: 35.0462 },
    ],
  },

  LB: {
    name: 'Lebanon',
    flag: '🇱🇧',
    capital: 'Beirut',
    currency: 'Lebanese Pound (LBP)',
    language: 'Arabic',
    timezone: 'Asia/Beirut',
    center: [33.8547, 35.8623],
    zoom: 8,
    advisoryLevel: 3,
    advisoryText: 'Reconsider travel due to terrorism, civil unrest, and armed conflict.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/lebanon-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/lebanon',
    emergency: { police: '112', fire: '175', ambulance: '140', redcross: '1400' },
    borderCrossings: [
      { name: 'Masnaa', status: 'open', note: 'Lebanon↔Syria, main crossing' },
      { name: 'Aboudiyeh', status: 'restricted', note: 'Lebanon↔Syria' },
      { name: 'Israel border', status: 'closed', note: 'All crossings closed' },
    ],
    healthNotices: [
      'Severe fuel and medicine shortages nationwide',
      'Hospital capacity critically strained',
      'Water safety concerns in several regions',
    ],
    newsFeed: [
      { name: 'L\'Orient Today', url: 'https://today.lorientlejour.com/rss', type: 'rss' },
      { name: 'Al Jazeera', url: 'https://www.aljazeera.com/xml/rss/all.xml', type: 'rss' },
    ],
    cities: [
      { name: 'Beirut', lat: 33.8938, lng: 35.5018 },
      { name: 'Tripoli', lat: 34.4367, lng: 35.8497 },
      { name: 'Sidon', lat: 33.5571, lng: 35.3729 },
      { name: 'Tyre', lat: 33.2704, lng: 35.2038 },
    ],
  },

  EG: {
    name: 'Egypt',
    flag: '🇪🇬',
    capital: 'Cairo',
    currency: 'Egyptian Pound (EGP)',
    language: 'Arabic',
    timezone: 'Africa/Cairo',
    center: [26.8206, 30.8025],
    zoom: 6,
    advisoryLevel: 2,
    advisoryText: 'Exercise increased caution. Higher risk in Sinai Peninsula and near Libyan border.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/egypt-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/egypt',
    emergency: { police: '122', fire: '180', ambulance: '123', tourist: '126' },
    borderCrossings: [
      { name: 'Rafah', status: 'restricted', note: 'Egypt↔Gaza, humanitarian use only' },
      { name: 'Taba', status: 'open', note: 'Egypt↔Israel' },
      { name: 'Wadi Halfa', status: 'open', note: 'Egypt↔Sudan' },
      { name: 'Salloum', status: 'open', note: 'Egypt↔Libya' },
    ],
    healthNotices: [
      'Hepatitis A and Typhoid vaccinations recommended',
      'Do not drink tap water',
      'Medical care good in Cairo, limited in rural areas',
    ],
    newsFeed: [
      { name: 'Egypt Independent', url: 'https://egyptindependent.com/feed/', type: 'rss' },
      { name: 'Al Jazeera', url: 'https://www.aljazeera.com/xml/rss/all.xml', type: 'rss' },
    ],
    cities: [
      { name: 'Cairo', lat: 30.0444, lng: 31.2357 },
      { name: 'Alexandria', lat: 31.2001, lng: 29.9187 },
      { name: 'Luxor', lat: 25.6872, lng: 32.6396 },
      { name: 'Sharm el-Sheikh', lat: 27.9158, lng: 34.3299 },
      { name: 'Hurghada', lat: 27.2579, lng: 33.8116 },
    ],
  },

  MX: {
    name: 'Mexico',
    flag: '🇲🇽',
    capital: 'Mexico City',
    currency: 'Mexican Peso (MXN)',
    language: 'Spanish',
    timezone: 'America/Mexico_City',
    center: [23.6345, -102.5528],
    zoom: 5,
    advisoryLevel: 3,
    advisoryText: 'Reconsider travel. Violent crime and kidnapping are widespread.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/mexico-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/mexico',
    emergency: { police: '911', fire: '911', ambulance: '911', tourist: '078' },
    borderCrossings: [
      { name: 'San Ysidro / Tijuana', status: 'open', note: 'USA↔Mexico, busiest land crossing' },
      { name: 'El Paso / Ciudad Juárez', status: 'open', note: 'USA↔Mexico' },
      { name: 'Laredo / Nuevo Laredo', status: 'open', note: 'USA↔Mexico' },
      { name: 'Tecún Umán', status: 'open', note: 'Mexico↔Guatemala' },
    ],
    healthNotices: [
      'Zika virus risk in some regions',
      'Do not drink tap water outside major cities',
      'Medical care excellent in Mexico City, varies elsewhere',
    ],
    newsFeed: [
      { name: 'Mexico News Daily', url: 'https://mexiconewsdaily.com/feed/', type: 'rss' },
      { name: 'Reuters Americas', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Mexico City', lat: 19.4326, lng: -99.1332 },
      { name: 'Guadalajara', lat: 20.6597, lng: -103.3496 },
      { name: 'Cancún', lat: 21.1619, lng: -86.8515 },
      { name: 'Tijuana', lat: 32.5149, lng: -117.0382 },
      { name: 'Monterrey', lat: 25.6866, lng: -100.3161 },
    ],
  },

  PK: {
    name: 'Pakistan',
    flag: '🇵🇰',
    capital: 'Islamabad',
    currency: 'Pakistani Rupee (PKR)',
    language: 'Urdu',
    timezone: 'Asia/Karachi',
    center: [30.3753, 69.3451],
    zoom: 5,
    advisoryLevel: 3,
    advisoryText: 'Reconsider travel due to terrorism and civil unrest.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/pakistan-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/pakistan',
    emergency: { police: '15', fire: '16', ambulance: '115', rescue: '1122' },
    borderCrossings: [
      { name: 'Wagah / Attari', status: 'restricted', note: 'Pakistan↔India, limited access' },
      { name: 'Torkham', status: 'open', note: 'Pakistan↔Afghanistan' },
      { name: 'Chaman', status: 'open', note: 'Pakistan↔Afghanistan south' },
    ],
    healthNotices: [
      'Polio vaccination required for entry',
      'Malaria risk in rural areas',
      'Water quality variable — bottled water recommended',
    ],
    newsFeed: [
      { name: 'Dawn', url: 'https://www.dawn.com/feeds/home', type: 'rss' },
      { name: 'Reuters Asia', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Karachi', lat: 24.8607, lng: 67.0011 },
      { name: 'Lahore', lat: 31.5204, lng: 74.3587 },
      { name: 'Islamabad', lat: 33.6844, lng: 73.0479 },
      { name: 'Peshawar', lat: 34.0151, lng: 71.5249 },
      { name: 'Quetta', lat: 30.1798, lng: 66.9750 },
    ],
  },

  TH: {
    name: 'Thailand',
    flag: '🇹🇭',
    capital: 'Bangkok',
    currency: 'Thai Baht (THB)',
    language: 'Thai',
    timezone: 'Asia/Bangkok',
    center: [15.8700, 100.9925],
    zoom: 6,
    advisoryLevel: 1,
    advisoryText: 'Exercise normal precautions. Higher risk in far south near Malaysian border.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/thailand-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/thailand',
    emergency: { police: '191', fire: '199', ambulance: '1669', tourist: '1155' },
    borderCrossings: [
      { name: 'Nong Khai', status: 'open', note: 'Thailand↔Laos' },
      { name: 'Mae Sai', status: 'open', note: 'Thailand↔Myanmar' },
      { name: 'Sadao', status: 'open', note: 'Thailand↔Malaysia' },
    ],
    healthNotices: [
      'Dengue fever risk year-round',
      'Medical care excellent in Bangkok',
      'Zika virus low risk',
    ],
    newsFeed: [
      { name: 'Bangkok Post', url: 'https://www.bangkokpost.com/rss/data/topstories.xml', type: 'rss' },
      { name: 'Reuters Asia', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Bangkok', lat: 13.7563, lng: 100.5018 },
      { name: 'Chiang Mai', lat: 18.7883, lng: 98.9853 },
      { name: 'Phuket', lat: 7.8804, lng: 98.3923 },
      { name: 'Pattaya', lat: 12.9236, lng: 100.8825 },
      { name: 'Koh Samui', lat: 9.5120, lng: 100.0136 },
    ],
  },

  FR: {
    name: 'France',
    flag: '🇫🇷',
    capital: 'Paris',
    currency: 'Euro (EUR)',
    language: 'French',
    timezone: 'Europe/Paris',
    center: [46.2276, 2.2137],
    zoom: 6,
    advisoryLevel: 1,
    advisoryText: 'Exercise normal precautions. Be alert to terrorism risk in public areas.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/france-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/france',
    emergency: { police: '17', fire: '18', ambulance: '15', general: '112' },
    borderCrossings: [
      { name: 'Schengen Area', status: 'open', note: 'Open borders with EU members' },
      { name: 'UK / Eurotunnel', status: 'open', note: 'France↔UK, passport required post-Brexit' },
    ],
    healthNotices: [
      'Excellent medical infrastructure',
      'EHIC/GHIC card recommended for EU/UK nationals',
      'No special vaccinations required',
    ],
    newsFeed: [
      { name: 'France 24', url: 'https://www.france24.com/en/rss', type: 'rss' },
      { name: 'Reuters Europe', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Paris', lat: 48.8566, lng: 2.3522 },
      { name: 'Marseille', lat: 43.2965, lng: 5.3698 },
      { name: 'Lyon', lat: 45.7640, lng: 4.8357 },
      { name: 'Nice', lat: 43.7102, lng: 7.2620 },
      { name: 'Bordeaux', lat: 44.8378, lng: -0.5792 },
    ],
  },

  JP: {
    name: 'Japan',
    flag: '🇯🇵',
    capital: 'Tokyo',
    currency: 'Japanese Yen (JPY)',
    language: 'Japanese',
    timezone: 'Asia/Tokyo',
    center: [36.2048, 138.2529],
    zoom: 6,
    advisoryLevel: 1,
    advisoryText: 'Exercise normal precautions. Be aware of earthquake and tsunami risk.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/japan-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/japan',
    emergency: { police: '110', fire: '119', ambulance: '119', coastguard: '118' },
    borderCrossings: [
      { name: 'Tokyo Narita Airport', status: 'open', note: 'Main international entry' },
      { name: 'Tokyo Haneda Airport', status: 'open', note: 'International terminal' },
      { name: 'Osaka Kansai Airport', status: 'open', note: 'International hub' },
    ],
    healthNotices: [
      'Excellent medical infrastructure',
      'Japanese encephalitis vaccination for rural visits',
      'Air quality generally excellent',
    ],
    newsFeed: [
      { name: 'Japan Times', url: 'https://www.japantimes.co.jp/feed/', type: 'rss' },
      { name: 'NHK World', url: 'https://www3.nhk.or.jp/rss/news/cat0.xml', type: 'rss' },
    ],
    cities: [
      { name: 'Tokyo', lat: 35.6762, lng: 139.6503 },
      { name: 'Osaka', lat: 34.6937, lng: 135.5023 },
      { name: 'Kyoto', lat: 35.0116, lng: 135.7681 },
      { name: 'Hiroshima', lat: 34.3853, lng: 132.4553 },
      { name: 'Sapporo', lat: 43.0618, lng: 141.3545 },
    ],
  },

  ZA: {
    name: 'South Africa',
    flag: '🇿🇦',
    capital: 'Pretoria',
    currency: 'South African Rand (ZAR)',
    language: 'Zulu / Xhosa / Afrikaans / English',
    timezone: 'Africa/Johannesburg',
    center: [-30.5595, 22.9375],
    zoom: 5,
    advisoryLevel: 2,
    advisoryText: 'Exercise increased caution due to crime and civil unrest.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/south-africa-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/south-africa',
    emergency: { police: '10111', fire: '10177', ambulance: '10177', general: '112' },
    borderCrossings: [
      { name: 'Beit Bridge', status: 'open', note: 'South Africa↔Zimbabwe' },
      { name: 'Maseru Bridge', status: 'open', note: 'South Africa↔Lesotho' },
      { name: 'Lebombo / Ressano Garcia', status: 'open', note: 'South Africa↔Mozambique' },
    ],
    healthNotices: [
      'Malaria risk in Limpopo and Mpumalanga',
      'HIV prevalence high — take standard precautions',
      'Medical care good in major cities',
    ],
    newsFeed: [
      { name: 'Daily Maverick', url: 'https://www.dailymaverick.co.za/feed/', type: 'rss' },
      { name: 'Reuters Africa', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Johannesburg', lat: -26.2041, lng: 28.0473 },
      { name: 'Cape Town', lat: -33.9249, lng: 18.4241 },
      { name: 'Durban', lat: -29.8587, lng: 31.0218 },
      { name: 'Pretoria', lat: -25.7479, lng: 28.2293 },
    ],
  },
};

// Advisory level config
const ADVISORY_LEVELS = {
  1: { label: 'Normal',    color: '#22c55e', bg: 'rgba(34,197,94,0.1)',   border: 'rgba(34,197,94,0.3)',   emoji: '🟢' },
  2: { label: 'Elevated',  color: '#f59e0b', bg: 'rgba(245,158,11,0.1)', border: 'rgba(245,158,11,0.3)', emoji: '🟡' },
  3: { label: 'High',      color: '#f97316', bg: 'rgba(249,115,22,0.1)', border: 'rgba(249,115,22,0.3)', emoji: '🟠' },
  4: { label: 'Critical',  color: '#ef4444', bg: 'rgba(239,68,68,0.1)',  border: 'rgba(239,68,68,0.3)',  emoji: '🔴' },
};

module.exports = { COUNTRIES, ADVISORY_LEVELS };

// Additional countries appended
const EXTRA_COUNTRIES = {
  IL: {
    name: 'Israel',
    flag: '🇮🇱',
    capital: 'Jerusalem',
    currency: 'Israeli New Shekel (ILS)',
    language: 'Hebrew / Arabic',
    timezone: 'Asia/Jerusalem',
    center: [31.5, 34.75],
    zoom: 8,
    advisoryLevel: 3,
    advisoryText: 'Reconsider travel. Ongoing armed conflict and terrorist threat.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/israel-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/israel',
    emergency: { police: '100', fire: '102', ambulance: '101', general: '112' },
    borderCrossings: [
      { name: 'Allenby Bridge / King Hussein', status: 'open', note: 'Israel↔Jordan' },
      { name: 'Yitzhak Rabin / Wadi Araba', status: 'open', note: 'Israel↔Jordan south' },
      { name: 'Rafah', status: 'closed', note: 'Gaza border, closed to civilians' },
      { name: 'Egypt / Taba', status: 'open', note: 'Israel↔Egypt' },
    ],
    healthNotices: [
      'Excellent medical infrastructure in major cities',
      'No special vaccinations required',
      'Air quality alerts possible during conflict operations',
    ],
    newsFeed: [
      { name: 'Times of Israel', url: 'https://www.timesofisrael.com/feed/', type: 'rss' },
      { name: 'Reuters ME', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Tel Aviv', lat: 32.0853, lng: 34.7818 },
      { name: 'Jerusalem', lat: 31.7683, lng: 35.2137 },
      { name: 'Haifa', lat: 32.7940, lng: 34.9896 },
      { name: 'Beer Sheva', lat: 31.2516, lng: 34.7915 },
    ],
  },

  IQ: {
    name: 'Iraq',
    flag: '🇮🇶',
    capital: 'Baghdad',
    currency: 'Iraqi Dinar (IQD)',
    language: 'Arabic / Kurdish',
    timezone: 'Asia/Baghdad',
    center: [33.2232, 43.6793],
    zoom: 6,
    advisoryLevel: 4,
    advisoryText: 'Do not travel. Terrorist groups, armed militias, and kidnapping risk throughout.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/iraq-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/iraq',
    emergency: { police: '104', fire: '115', ambulance: '122' },
    borderCrossings: [
      { name: 'Trebil', status: 'open', note: 'Iraq↔Jordan' },
      { name: 'Munthiriyah / Zurbatiyah', status: 'restricted', note: 'Iraq↔Iran' },
      { name: 'Safwan / Abdali', status: 'open', note: 'Iraq↔Kuwait' },
      { name: 'Turkey borders', status: 'restricted', note: 'Variable, check current status' },
    ],
    healthNotices: [
      'Medical infrastructure severely limited outside Baghdad',
      'Cholera risk in some regions — drink bottled water only',
      'Extreme heat — hydration critical May-September',
    ],
    newsFeed: [
      { name: 'Al Jazeera', url: 'https://www.aljazeera.com/xml/rss/all.xml', type: 'rss' },
      { name: 'Reuters ME', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Baghdad', lat: 33.3128, lng: 44.3615 },
      { name: 'Basra', lat: 30.5085, lng: 47.7804 },
      { name: 'Erbil', lat: 36.1901, lng: 44.0091 },
      { name: 'Mosul', lat: 36.3350, lng: 43.1189 },
    ],
  },

  CO: {
    name: 'Colombia',
    flag: '🇨🇴',
    capital: 'Bogotá',
    currency: 'Colombian Peso (COP)',
    language: 'Spanish',
    timezone: 'America/Bogota',
    center: [4.5709, -74.2973],
    zoom: 6,
    advisoryLevel: 3,
    advisoryText: 'Reconsider travel. Armed groups operate in many rural areas. Crime is widespread.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/colombia-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/colombia',
    emergency: { police: '112', fire: '119', ambulance: '125', tourist: '01800-112' },
    borderCrossings: [
      { name: 'Cúcuta / San Antonio', status: 'open', note: 'Colombia↔Venezuela, limited' },
      { name: 'Ipiales / Tulcán', status: 'open', note: 'Colombia↔Ecuador' },
      { name: 'Leticia', status: 'open', note: 'Colombia↔Brazil/Peru, river crossing' },
    ],
    healthNotices: [
      'Yellow fever vaccination required for jungle areas',
      'Zika and dengue risk, especially in coastal areas',
      'Altitude sickness possible in Bogotá and Andean cities',
    ],
    newsFeed: [
      { name: 'Colombia Reports', url: 'https://colombiareports.com/feed/', type: 'rss' },
      { name: 'Reuters Americas', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Bogotá', lat: 4.7110, lng: -74.0721 },
      { name: 'Medellín', lat: 6.2442, lng: -75.5812 },
      { name: 'Cartagena', lat: 10.3910, lng: -75.4794 },
      { name: 'Cali', lat: 3.4516, lng: -76.5320 },
    ],
  },

  NG: {
    name: 'Nigeria',
    flag: '🇳🇬',
    capital: 'Abuja',
    currency: 'Nigerian Naira (NGN)',
    language: 'English',
    timezone: 'Africa/Lagos',
    center: [9.0820, 8.6753],
    zoom: 6,
    advisoryLevel: 3,
    advisoryText: 'Reconsider travel. Crime, terrorism, and civil unrest. Kidnapping risk is high.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/nigeria-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/nigeria',
    emergency: { police: '199', fire: '199', ambulance: '199', general: '112' },
    borderCrossings: [
      { name: 'Seme / Krake', status: 'open', note: 'Nigeria↔Benin' },
      { name: 'Maigatari', status: 'open', note: 'Nigeria↔Niger' },
      { name: 'Mfun', status: 'restricted', note: 'Nigeria↔Cameroon' },
    ],
    healthNotices: [
      'Yellow fever vaccination required for entry',
      'Malaria risk throughout — prophylaxis recommended',
      'Lassa fever risk in some rural areas',
      'Medical facilities very limited outside major cities',
    ],
    newsFeed: [
      { name: 'Punch Nigeria', url: 'https://punchng.com/feed/', type: 'rss' },
      { name: 'Reuters Africa', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Lagos', lat: 6.5244, lng: 3.3792 },
      { name: 'Abuja', lat: 9.0765, lng: 7.3986 },
      { name: 'Kano', lat: 12.0022, lng: 8.5920 },
      { name: 'Port Harcourt', lat: 4.8156, lng: 7.0498 },
    ],
  },

  IN: {
    name: 'India',
    flag: '🇮🇳',
    capital: 'New Delhi',
    currency: 'Indian Rupee (INR)',
    language: 'Hindi / English',
    timezone: 'Asia/Kolkata',
    center: [20.5937, 78.9629],
    zoom: 5,
    advisoryLevel: 2,
    advisoryText: 'Exercise increased caution. Terrorist attacks and civil unrest have occurred. Kashmir region — do not travel.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/india-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/india',
    emergency: { police: '100', fire: '101', ambulance: '102', women: '1091' },
    borderCrossings: [
      { name: 'Wagah / Attari', status: 'restricted', note: 'India↔Pakistan, limited access' },
      { name: 'Petrapole / Benapole', status: 'open', note: 'India↔Bangladesh' },
      { name: 'Raxaul / Birgunj', status: 'open', note: 'India↔Nepal' },
    ],
    healthNotices: [
      'Typhoid, Hepatitis A vaccination recommended',
      'Malaria risk in some rural areas',
      'Drink bottled water only',
      'Air quality poor in major cities — N95 mask recommended',
    ],
    newsFeed: [
      { name: 'Times of India', url: 'https://timesofindia.indiatimes.com/rssfeeds/296589292.cms', type: 'rss' },
      { name: 'Reuters Asia', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'New Delhi', lat: 28.6139, lng: 77.2090 },
      { name: 'Mumbai', lat: 19.0760, lng: 72.8777 },
      { name: 'Bangalore', lat: 12.9716, lng: 77.5946 },
      { name: 'Chennai', lat: 13.0827, lng: 80.2707 },
      { name: 'Kolkata', lat: 22.5726, lng: 88.3639 },
    ],
  },

  BR: {
    name: 'Brazil',
    flag: '🇧🇷',
    capital: 'Brasília',
    currency: 'Brazilian Real (BRL)',
    language: 'Portuguese',
    timezone: 'America/Sao_Paulo',
    center: [-14.2350, -51.9253],
    zoom: 4,
    advisoryLevel: 2,
    advisoryText: 'Exercise increased caution due to crime. Some areas have increased risk.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/brazil-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/brazil',
    emergency: { police: '190', fire: '193', ambulance: '192', general: '911' },
    borderCrossings: [
      { name: 'Foz do Iguaçu / Ciudad del Este', status: 'open', note: 'Brazil↔Paraguay (triple border)' },
      { name: 'Santana do Livramento / Rivera', status: 'open', note: 'Brazil↔Uruguay' },
      { name: 'Tabatinga / Leticia', status: 'open', note: 'Brazil↔Colombia, river crossing' },
    ],
    healthNotices: [
      'Yellow fever vaccination recommended',
      'Dengue, Zika, and chikungunya risk',
      'Excellent medical care in São Paulo and Rio de Janeiro',
    ],
    newsFeed: [
      { name: 'Brazil Reports', url: 'https://brazilreports.com/feed/', type: 'rss' },
      { name: 'Reuters Americas', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'São Paulo', lat: -23.5505, lng: -46.6333 },
      { name: 'Rio de Janeiro', lat: -22.9068, lng: -43.1729 },
      { name: 'Brasília', lat: -15.8267, lng: -47.9218 },
      { name: 'Salvador', lat: -12.9714, lng: -38.5014 },
    ],
  },

  KE: {
    name: 'Kenya',
    flag: '🇰🇪',
    capital: 'Nairobi',
    currency: 'Kenyan Shilling (KES)',
    language: 'Swahili / English',
    timezone: 'Africa/Nairobi',
    center: [-0.0236, 37.9062],
    zoom: 6,
    advisoryLevel: 2,
    advisoryText: 'Exercise increased caution. Terrorism risk, particularly near the Somali border.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/kenya-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/kenya',
    emergency: { police: '999', fire: '999', ambulance: '999', general: '112' },
    borderCrossings: [
      { name: 'Namanga', status: 'open', note: 'Kenya↔Tanzania' },
      { name: 'Moyale', status: 'open', note: 'Kenya↔Ethiopia' },
      { name: 'Lungalunga', status: 'open', note: 'Kenya↔Tanzania coast' },
    ],
    healthNotices: [
      'Yellow fever vaccination required if coming from endemic area',
      'Malaria risk — prophylaxis recommended',
      'Typhoid and Hepatitis A vaccination recommended',
    ],
    newsFeed: [
      { name: 'Daily Nation Kenya', url: 'https://nation.africa/kenya/rss.xml', type: 'rss' },
      { name: 'Reuters Africa', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Nairobi', lat: -1.2921, lng: 36.8219 },
      { name: 'Mombasa', lat: -4.0435, lng: 39.6682 },
      { name: 'Kisumu', lat: -0.0917, lng: 34.7679 },
    ],
  },

  PH: {
    name: 'Philippines',
    flag: '🇵🇭',
    capital: 'Manila',
    currency: 'Philippine Peso (PHP)',
    language: 'Filipino / English',
    timezone: 'Asia/Manila',
    center: [12.8797, 121.7740],
    zoom: 6,
    advisoryLevel: 2,
    advisoryText: 'Exercise increased caution. Terrorist attacks and kidnappings in Mindanao.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/philippines-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/philippines',
    emergency: { police: '117', fire: '117', ambulance: '117', general: '911' },
    borderCrossings: [
      { name: 'Manila Ninoy Aquino Airport', status: 'open', note: 'Main international hub' },
      { name: 'Cebu Mactan Airport', status: 'open', note: 'Second international hub' },
    ],
    healthNotices: [
      'Dengue fever risk year-round',
      'Typhoid vaccination recommended',
      'Typhoon season June-November — monitor warnings',
    ],
    newsFeed: [
      { name: 'Philippine Daily Inquirer', url: 'https://inquirer.net/feed', type: 'rss' },
      { name: 'Reuters Asia', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Manila', lat: 14.5995, lng: 120.9842 },
      { name: 'Cebu City', lat: 10.3157, lng: 123.8854 },
      { name: 'Davao', lat: 7.1907, lng: 125.4553 },
    ],
  },

  TR: {
    name: 'Turkey',
    flag: '🇹🇷',
    capital: 'Ankara',
    currency: 'Turkish Lira (TRY)',
    language: 'Turkish',
    timezone: 'Europe/Istanbul',
    center: [38.9637, 35.2433],
    zoom: 6,
    advisoryLevel: 2,
    advisoryText: 'Exercise increased caution. Terrorist attacks have targeted tourist areas.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/turkey-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/turkey',
    emergency: { police: '155', fire: '110', ambulance: '112', general: '112' },
    borderCrossings: [
      { name: 'Kapıkule / Kapitan Andreevo', status: 'open', note: 'Turkey↔Bulgaria (main EU route)' },
      { name: 'Pazarkule / Kastanies', status: 'restricted', note: 'Turkey↔Greece, limited' },
      { name: 'Bab al-Hawa', status: 'restricted', note: 'Turkey↔Syria, humanitarian only' },
    ],
    healthNotices: [
      'No special vaccinations required for most areas',
      'Medical care excellent in Istanbul and major cities',
      'Earthquake risk — know your building\'s safety',
    ],
    newsFeed: [
      { name: 'Hurriyet Daily News', url: 'https://www.hurriyetdailynews.com/rss/', type: 'rss' },
      { name: 'Reuters Europe', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Istanbul', lat: 41.0082, lng: 28.9784 },
      { name: 'Ankara', lat: 39.9334, lng: 32.8597 },
      { name: 'Antalya', lat: 36.8969, lng: 30.7133 },
      { name: 'Izmir', lat: 38.4192, lng: 27.1287 },
    ],
  },

  MA: {
    name: 'Morocco',
    flag: '🇲🇦',
    capital: 'Rabat',
    currency: 'Moroccan Dirham (MAD)',
    language: 'Arabic / French / Berber',
    timezone: 'Africa/Casablanca',
    center: [31.7917, -7.0926],
    zoom: 6,
    advisoryLevel: 2,
    advisoryText: 'Exercise increased caution due to terrorism. Remote areas carry higher risk.',
    stateDeptUrl: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/morocco-travel-advisory.html',
    fcoUrl: 'https://www.gov.uk/foreign-travel-advice/morocco',
    emergency: { police: '19', fire: '15', ambulance: '15', gendarmerie: '177' },
    borderCrossings: [
      { name: 'Bab Sebta (Ceuta)', status: 'open', note: 'Morocco↔Spain (EU enclave)' },
      { name: 'Beni Enzar (Melilla)', status: 'open', note: 'Morocco↔Spain (EU enclave)' },
      { name: 'Mauritania border', status: 'open', note: 'Morocco↔Mauritania, Sahara crossing' },
    ],
    healthNotices: [
      'Hepatitis A vaccination recommended',
      'Avoid tap water — use bottled or filtered',
      'Good medical facilities in major cities',
    ],
    newsFeed: [
      { name: 'Morocco World News', url: 'https://www.moroccoworldnews.com/feed/', type: 'rss' },
      { name: 'Reuters Africa', url: 'https://feeds.reuters.com/reuters/worldNews', type: 'rss' },
    ],
    cities: [
      { name: 'Casablanca', lat: 33.5731, lng: -7.5898 },
      { name: 'Marrakech', lat: 31.6295, lng: -7.9811 },
      { name: 'Rabat', lat: 34.0209, lng: -6.8416 },
      { name: 'Fez', lat: 34.0181, lng: -5.0078 },
    ],
  },
};

// Merge extra countries into COUNTRIES
Object.assign(COUNTRIES, EXTRA_COUNTRIES);
